### ISSUE TITLE
hardcoded paths in project

### ISSUE THREAD

**Issue by brean** [cesardeazevedo/Unity3D-Python-Editor#1]
unity can not finde some of the files e.g. "c:\users\iCesar\Develop...\RigidbodyExample.py" could not be found

**Comment by cesardeazevedo** [comment]
this fixes it, thanks for report. https://github.com/cesardeazevedo/Unity3D-Python-Editor/blob/24cdb9ce71cb66e2dd05a63e603273f83844dfbf/Assets/scenes/Scene.unity#L510
